# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/jlinc-node

    docker:
      # specify the version you desire here
      - image: node:18.13.0
        environment:
        - NODE_ENV: test
        - DATABASE_HOST: postgresql://root@127.0.0.1
        - PGHOST: 127.0.0.1
        - PGUSER: root
      - image: circleci/postgres:9.6-alpine
        environment:
        - POSTGRES_USER: root

    steps:
      - run: apt-get clean
      - run: apt-get update
      - run: apt-get install -y postgresql-client

      - checkout
      - run: git submodule update --init

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - node_modules-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

      - run:
          name: compress coverage
          command: tar -zcvf coverage.tgz coverage/

      - store_artifacts:
          path: ./coverage.tgz
          destination: coverage.tgz
